language: node_js
sudo: true
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - ffmpeg
node_js:
  - 10
  - 12